apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fdmhn07cb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fdmhn07cb-python 
  name: fdmhn07cb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fdmhn07cb-python 
