apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fdmhn07cb-python 
  janus-idp.io/tekton: fdmhn07cb-python
  backstage.io/kubernetes-id: fdmhn07cb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fdmhn07cb-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  